// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AutoSuggestion: typeof import('./src/components/code/auto-suggestion.md')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ChapterHeader: typeof import('./src/components/ChapterHeader.vue')['default']
    DynamicData: typeof import('./src/components/DynamicData.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ExampleDynamicData: typeof import('./src/components/examples/ExampleDynamicData.vue')['default']
    HeroTabs: typeof import('./src/components/HeroTabs.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    Link: typeof import('./src/components/Link.vue')['default']
  }
}

export { }
