// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AutoSuggestion: typeof import('./src/components/code/auto-suggestion.md')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    ChapterFlexibility: typeof import('./src/components/sections/ChapterFlexibility.vue')['default']
    ChapterHeader: typeof import('./src/components/common/ChapterHeader.vue')['default']
    ChapterHybridity: typeof import('./src/components/sections/ChapterHybridity.vue')['default']
    ChapterScripting: typeof import('./src/components/sections/ChapterScripting.vue')['default']
    DynamicData: typeof import('./src/components/DynamicData.vue')['default']
    Editor: typeof import('./src/components/common/Editor.vue')['default']
    ExampleDynamicData: typeof import('./src/components/examples/ExampleDynamicData.vue')['default']
    ExampleScripting: typeof import('./src/components/examples/ExampleScripting.vue')['default']
    Hero: typeof import('./src/components/sections/Hero.vue')['default']
    HeroTabs: typeof import('./src/components/common/HeroTabs.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    Link: typeof import('./src/components/common/Link.vue')['default']
    SectionFlexibility: typeof import('./src/components/sections/SectionFlexibility.vue')['default']
    SectionHybridity: typeof import('./src/components/sections/SectionHybridity.vue')['default']
    SectionScripting: typeof import('./src/components/sections/SectionScripting.vue')['default']
    SectionShorts: typeof import('./src/components/sections/SectionShorts.vue')['default']
    Step: typeof import('./src/components/Step.vue')['default']
  }
}

export { }
