// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common/Button.vue')['default']
    Card: typeof import('./src/components/common/Card.vue')['default']
    ChapterHeader: typeof import('./src/components/common/ChapterHeader.vue')['default']
    Editor: typeof import('./src/components/common/Editor.vue')['default']
    ExampleScripting: typeof import('./src/components/examples/ExampleScripting.vue')['default']
    Fiderio: typeof import('./src/components/common/Fiderio.vue')['default']
    Hero: typeof import('./src/components/sections/Hero.vue')['default']
    HeroTabs: typeof import('./src/components/common/HeroTabs.vue')['default']
    IconEquitations: typeof import('./src/components/icons/IconEquitations.vue')['default']
    IconExport: typeof import('./src/components/icons/IconExport.vue')['default']
    IconFamiliar: typeof import('./src/components/icons/IconFamiliar.vue')['default']
    IconFileSplitting: typeof import('./src/components/icons/IconFileSplitting.vue')['default']
    IconGit: typeof import('./src/components/icons/IconGit.vue')['default']
    IconLocal: typeof import('./src/components/icons/IconLocal.vue')['default']
    IconPlugins: typeof import('./src/components/icons/IconPlugins.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconPreview: typeof import('./src/components/icons/IconPreview.vue')['default']
    IconTheme: typeof import('./src/components/icons/IconTheme.vue')['default']
    InlineCode: typeof import('./src/components/common/InlineCode.vue')['default']
    Link: typeof import('./src/components/common/Link.vue')['default']
    Marked: typeof import('./src/components/common/Marked.vue')['default']
    PartFooter: typeof import('./src/components/sections/PartFooter.vue')['default']
    SectionFlexibility: typeof import('./src/components/sections/SectionFlexibility.vue')['default']
    SectionHybridity: typeof import('./src/components/sections/SectionHybridity.vue')['default']
    SectionScripting: typeof import('./src/components/sections/SectionScripting.vue')['default']
    SectionShorts: typeof import('./src/components/sections/SectionShorts.vue')['default']
    SectionTemplates: typeof import('./src/components/sections/SectionTemplates.vue')['default']
    Step: typeof import('./src/components/common/Step.vue')['default']
  }
}

export { }
